### ISSUE TITLE
Unresolved dependencies on fresh AEM 6.3.1

### ISSUE THREAD

**Issue by dmitry-cherkas** [Adobe-Marketing-Cloud/aem-guides-wknd#12]
Steps to reproduce:
1. Install AEM 6.3
2. Install AEM 6.3 SP1
3. Download sources from https://github.com/Adobe-Marketing-Cloud/aem-guides-wknd/releases (link at the bottom of the page https://helpx.adobe.com/experience-manager/kt/sites/using/getting-started-wknd-tutorial-develop/part5.html)
4. Build/deploy project
5. Open http://localhost:4512/editor.html/content/wknd/en.html

**Expected:** page contents is rendered
**Actual:** page contents not rendered, white screen

Additional details:
![image](https://user-images.githubusercontent.com/3441528/36126631-6e4356ac-106a-11e8-94d8-79590f041114.png)

![image](https://user-images.githubusercontent.com/3441528/36126652-83497766-106a-11e8-8c4a-d118a3d60cd1.png)

**Comment by godanny86** [comment]
it looks like Core Components 2.0 did not get installed correctly. Can you check Package Manager to see if they got uploaded? <localhost>/crx/packmgr/index.jsp

**Comment by godanny86** [comment]
actually reviewing your setup you need [FP-20593](https://www.adobeaemcloud.com/content/marketplace/marketplaceProxy.html?packagePath=/content/companies/public/adobe/packages/cq630/featurepack/cq-6.3.0-featurepack-20593) In addition to SP1. This is mentioned in [PT1](https://helpx.adobe.com/experience-manager/kt/sites/using/getting-started-wknd-tutorial-develop/part1.html) but I will update the overview as well.

**Comment by dmitry-cherkas** [comment]
Hi, @godanny86 , thanks for the hint. I've installed FP-20593 but it seems that it made things even worse (see complete log attached):
[error.log](https://github.com/Adobe-Marketing-Cloud/aem-guides-wknd/files/1719324/error.log)

Are there some other prerequisites I'm missing?

**Comment by godanny86** [comment]
Ah do you have Java 1.8? I'm seeing this in the logs `Unresolved requirements: [[com.adobe.cq.core.wcm.components.core [517](R 517.1)] osgi.ee; (&(osgi.ee=JavaSE)(version=1.8))]`

**Comment by dmitry-cherkas** [comment]
Well, I might have messed up with JAVA_HOME. Now that I verified, I'm running on 1.8 there is only one unresolved dependency left (not directly related to this tutorial, but just for reference):
```
13.02.2018 17:45:27.881 *ERROR* [FelixStartLevel] ERROR: Bundle '519' Error starting jcrinstall:/apps/weretail/install/we.retail.core-2.0.2.jar (org.osgi.framework.BundleException: Unable to resolve com.adobe.cq.sample.we.retail.core [519](R 519.0): missing requirement [com.adobe.cq.sample.we.retail.core [519](R 519.0)] osgi.wiring.package; (&(osgi.wiring.package=com.adobe.cq.wcm.core.components.models.form)(version>=13.0.0)(!(version>=14.0.0))) Unresolved requirements: [[com.adobe.cq.sample.we.retail.core [519](R 519.0)] osgi.wiring.package; (&(osgi.wiring.package=com.adobe.cq.wcm.core.components.models.form)(version>=13.0.0)(!(version>=14.0.0)))])
org.osgi.framework.BundleException: Unable to resolve com.adobe.cq.sample.we.retail.core [519](R 519.0): missing requirement [com.adobe.cq.sample.we.retail.core [519](R 519.0)] osgi.wiring.package; (&(osgi.wiring.package=com.adobe.cq.wcm.core.components.models.form)(version>=13.0.0)(!(version>=14.0.0))) Unresolved requirements: [[com.adobe.cq.sample.we.retail.core [519](R 519.0)] osgi.wiring.package; (&(osgi.wiring.package=com.adobe.cq.wcm.core.components.models.form)(version>=13.0.0)(!(version>=14.0.0)))]
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4112)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2118)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1372)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
        at java.lang.Thread.run(Thread.java:748)
13.02.2018 17:45:30.962 *INFO * [main] Startup completed
```
Looks like we.retail has a dependency on core.components v1.

As initial issue is now resolved, I'm closing the ticket. @godanny86 , thanks for your help!

**Comment by godanny86** [comment]
No problem. Thanks for opening the issue @dmitry-cherkas! I expect a core.components v2 version of We.Retail will be released very soon.
