### ISSUE TITLE
LESS does not get compiled into CSS on AEM 6.4

### ISSUE THREAD

**Issue by dmitry-cherkas** [Adobe-Marketing-Cloud/aem-guides-wknd#13]
Steps to reproduce:

1. Install AEM 6.4
2. Download sources from https://github.com/Adobe-Marketing-Cloud/aem-guides-wknd/releases (link at the bottom of the page https://helpx.adobe.com/experience-manager/kt/sites/using/getting-started-wknd-tutorial-develop/part5.html)
3. Build/deploy project
4. Open http://localhost:4512/editor.html/content/wknd/en.html

**Expected:** page contents rendered, visual styles are applied to navigation elements
**Actual:** page contents are rendered, but visual styles are not applied

**Additional details:**
LESS does not get compiled into CSS:
![image](https://user-images.githubusercontent.com/3441528/36126705-be936264-106a-11e8-9241-e336f1da15e0.png)

**Comment by godanny86** [comment]
Hi @dmitry-cherkas, yes this is a known issue the grid_base.less was moved in 6.4. Check out: https://github.com/Adobe-Marketing-Cloud/aem-guides-wknd/compare/pre-release/6.4 to see the fix for 6.4

**Comment by esr360** [comment]
This is the top result on google for "aem compile less" and it is of no help whatsoever. Where's the offical docs on this?

**Comment by scorpionking2k5** [comment]
@esr360 if changing the grid_path did not fix your issue, then make sure you're including either bootstrap's source files (not compiled) or the variable.less file. 
The missing variables are in these files.
