### ISSUE TITLE
No root layout container when creating template

### ISSUE THREAD

**Issue by bmon** [Adobe-Marketing-Cloud/aem-guides-wknd#17]
Hi,

I've been following the WKND guide, and after deploying the chapter 2 code to my local, I've been unable to create templates as there is no Root Layout object in the template editor. This is also true for the other templates that were created as part of chapter 2: when I open them they are completely empty and there are no components or layouts.

![image](https://user-images.githubusercontent.com/2115272/38343198-d310d810-38c5-11e8-9816-fcd807dc31a9.png)

I've verified the root layout object is actually defined in the code, it seems to be done correctly.

Running AEM 6.3, replicated the issue on 6.3.0 and SP2.

Thanks!

**Comment by godanny86** [comment]
@bmon Is there anything in the error.log? It could be that a node in the template is not pointing correctly to a component `sling:resourceType`. I'd look for some log statements like: `No renderer for extension html, cannot render resource JcrNodeResource, type=` in the error.log to try and narrow down where the error is.

**Comment by godanny86** [comment]
@bmon the tutorial has recently been updated to use the new Maven AEM project archetype 13. I think you will find that many of the manual steps have been eliminated from parts 1 and 2. If you don't mind restarting the tutorial hopefully you won't run into this error...

**Comment by bmon** [comment]
I'll give it a shot when I get a chance. Thanks for the update!

**Comment by godanny86** [comment]
also just a heads up: issue #19
