### ISSUE TITLE
Page Properties Issue on Creation

### ISSUE THREAD

**Issue by RPDiC** [Adobe-Marketing-Cloud/aem-guides-wknd#18]
I came across an issue when I cloned the project before starting part 2 of the tutorial. I was not able to create a page due to the 'basic' and 'advanced' tabs of the page properties not existing. The only tab available was 'social media'.

**Comment by godanny86** [comment]
@RPDiC what version of AEM was used? 6.4 or 6.3+SP2? 

A few more questions:
Did you notice this using the Content Page Template?
After cloning the repo, did you checkout `part/1-project-setup` and then deployed that to a local AEM instance using `mvn -PautoInstallPackage clean install` ?

**Comment by RPDiC** [comment]
I'm using version 6.3 +SP2.

I noticed it when I tried creating a page using the Landing Page Template; however, it was not limited to this. 

I cloned https://github.com/Adobe-Marketing-Cloud/aem-guides-wknd.git
and then deployed using `mvn -PautoInstallPackage clean install`.

Which branch am I supposed to checkout? I apologize, I haven't used git in a while...

**Comment by godanny86** [comment]
@RPDiC no problem! When you clone the repo you will be on the master branch, which is actually the finished code for the entire tutorial for AEM 6.4. There is another branch `6-3/master` that has the finished code for AEM 6.3 + SP2. For reference to checkout a new branch you can use the checkout command:

```
git checkout part/1-project-setup
```

You can also just download the packages directly from: https://github.com/Adobe-Marketing-Cloud/aem-guides-wknd/releases. I'd also recommend clearing your browser cache to make sure there is no css/js from a different version of AEM conflicting...

**Comment by godanny86** [comment]
also just a heads up: issue #19

**Comment by RPDiC** [comment]
@godanny86 great! The original problem was fixed. Then I had the root layout container issue, but the feature pack fixed it. Thanks!

**Comment by godanny86** [comment]
awesome! Thanks @RPDiC
