### ISSUE TITLE
AEM6.4 - aem-guides-wknd - Project is having build and dependency issues

### ISSUE THREAD

**Issue by munikmca** [Adobe-Marketing-Cloud/aem-guides-wknd#21]
Hi,

I have tried to clone and build(mvn clean install -PautoInstallPackage) this project, but getting maven dependency issues. Please refer the error log below.

#############################

[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Unresolveable build extension: Plugin com.day.jcr.vault:content-package-maven-plugin:0.5.1 or one of its dependencies could not be resolved: Could not find artifact com.day.jcr.vault:content-package-maven-plugin:jar:0.5.1 in central (https://repo.maven.apache.org/maven2) @ 
[ERROR] Unknown packaging: content-package @ com.adobe.aem.guides:aem-guides-wknd.ui.apps:[unknown-version], /Users/brian.walker/ServiceNow/git-projects/aem-guides-wknd/ui.apps/pom.xml, line 34, column 16
[ERROR] Unresolveable build extension: Plugin com.day.jcr.vault:content-package-maven-plugin:0.5.1 or one of its dependencies could not be resolved: Could not find artifact com.day.jcr.vault:content-package-maven-plugin:jar:0.5.1 in central (https://repo.maven.apache.org/maven2) @ 
[ERROR] Unknown packaging: content-package @ com.adobe.aem.guides:aem-guides-wknd.ui.content:[unknown-version], /Users/brian.walker/ServiceNow/git-projects/aem-guides-wknd/ui.content/pom.xml, line 34, column 16
 @ 
[ERROR] The build could not read 2 projects -> [Help 1]
[ERROR]   
[ERROR]   The project com.adobe.aem.guides:aem-guides-wknd.ui.apps:0.0.1-SNAPSHOT (/Users/brian.walker/ServiceNow/git-projects/aem-guides-wknd/ui.apps/pom.xml) has 2 errors
[ERROR]     Unresolveable build extension: Plugin com.day.jcr.vault:content-package-maven-plugin:0.5.1 or one of its dependencies could not be resolved: Could not find artifact com.day.jcr.vault:content-package-maven-plugin:jar:0.5.1 in central (https://repo.maven.apache.org/maven2) -> [Help 2]
[ERROR]     Unknown packaging: content-package @ com.adobe.aem.guides:aem-guides-wknd.ui.apps:[unknown-version], /Users/brian.walker/ServiceNow/git-projects/aem-guides-wknd/ui.apps/pom.xml, line 34, column 16
[ERROR]   
[ERROR]   The project com.adobe.aem.guides:aem-guides-wknd.ui.content:0.0.1-SNAPSHOT (/Users/brian.walker/ServiceNow/git-projects/aem-guides-wknd/ui.content/pom.xml) has 2 errors
[ERROR]     Unresolveable build extension: Plugin com.day.jcr.vault:content-package-maven-plugin:0.5.1 or one of its dependencies could not be resolved: Could not find artifact com.day.jcr.vault:content-package-maven-plugin:jar:0.5.1 in central (https://repo.maven.apache.org/maven2) -> [Help 2]
[ERROR]     Unknown packaging: content-package @ com.adobe.aem.guides:aem-guides-wknd.ui.content:[unknown-version], /Users/brian.walker/ServiceNow/git-projects/aem-guides-wknd/ui.content/pom.xml, line 34, column 16
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/PluginManagerException

**Comment by godanny86** [comment]
Hi @munikmca,
Have you set up a settings.xml file beneath your ~/.m2 directory? In it you need to add the Adobe Public Repos to your settings file. See https://helpx.adobe.com/experience-manager/kb/SetUpTheAdobeMavenRepository.html for details. 

Let me know if this fixes the issue and I will update the tutorial instructions in Part 1.

**Comment by pankajchhatri** [comment]
Use mvn -PautoInstallPackage -Padobe-public clean install command.

**Comment by IlOvOII** [comment]
Hi @godanny86 
I have the same problem, but I still can't solve it according to what you said.

**Comment by IlOvOII** [comment]
Hello @pankajchhatri 
Can you solve this problem? I didn't succeed in using your suggested method.

**Comment by godanny86** [comment]
@IlOvOII you have updated your ~/.m2/settings file to include repo.adobe.com?

I am traveling this month so my response may be delayed. @davidjgonzalez might also be able to assist...

**Comment by IlOvOII** [comment]
Hello @davidjgonzalez
Yes, I had update setting file.But there's the same problem.

**Comment by davidjgonzalez** [comment]
@IlOvOII  can you paste the profile from your ~/.m2/settings.xml for the adobe public repo?
Since your failing on resolving a plugin dependency, I assume you've doubled checked that the pluginReposistory configuration?

Mine looks like ...

```
        <profile>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <id>adobe-public</id>
			<repositories>
                <repository>
                    <id>adobe-public-releases</id>
                    <name>Adobe Public Repository</name>
                    <url>https://repo.adobe.com/nexus/content/groups/public/</url>
                    <layout>default</layout>
                </repository>
		        <repository>
		             <id>central</id>
		             <url>http://repo1.maven.org/maven2/</url>
		             <layout>default</layout>
		             <releases>
		               <enabled>true</enabled>
		               <updatePolicy>never</updatePolicy>
		             </releases>
		             <snapshots>
		               <enabled>false</enabled>
		             </snapshots>
		           </repository>						
            </repositories>
            <pluginRepositories>
                <pluginRepository>
                    <id>adobe-public-releases</id>
                    <name>Adobe Public Repository</name>
                    <url>https://repo.adobe.com/nexus/content/groups/public/</url>
                    <layout>default</layout>
                </pluginRepository>
            </pluginRepositories>
        </profile>
```

**Comment by davidjgonzalez** [comment]
@IlOvOII use `mvn help:all-profiles -Padobe-public -PautoInstallPackage` to verify that your profile is indeed active under that name - you should see:  `Profile Id: adobe-public (Active: true , Source: settings.xml)`

If not, theres a problem w your settings.xml definition. 

You can also try:

1. Set `<activeByDefault>true</activeByDefault>` and `<activeProfile>adobe-public</activeProfile>` - this should FORCE that profile to be true no matter what.. you can again validate this by running `mvn help:all-profiles` after making that change. 

2. Comment our your adobe-public <profile> and copy/paste mine in .. i dont see why yours wouldnt work, but nothing is jumping out as the obvious problem either.

**Comment by IlOvOII** [comment]
@davidjgonzalez 
Thank you very much! I successfully deployed it after using your advice 1.

**Comment by dhulipudi** [comment]
I am also getting same issue - I have maven 3.3.9 and my settings.xml is below.

=================settings.xml===========
<?xml version="1.0" encoding="UTF-8"?>
 

 

<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
  
 
  
 
  
 
  
  <pluginGroups>
    
  </pluginGroups>
 
  
  <proxies>
    
  </proxies>
 
  
  <servers>
    
     
    
  </servers>
 
  
  <mirrors>
    
  </mirrors>
   
  
  <profiles>
    
 
    
   
 



<profile>
    <id>adobe-public</id>
 
    <activation>
        <activeByDefault>true</activeByDefault>
    </activation>
 
    <properties>
 
        <releaseRepository-Id>adobe-public-releases</releaseRepository-Id>
        <releaseRepository-Name>Adobe Public
            Releases</releaseRepository-Name>
 
        <releaseRepository-URL>https://repo.adobe.com/nexus/content/groups/public</releaseRepository-URL>
    </properties>
 
    <repositories>
        <repository>
            <id>adobe-public-releases</id>
            <name>Adobe Basel Public Repository</name>
            <url>https://repo.adobe.com/nexus/content/groups/public</url>
            <releases>
                <enabled>true</enabled>
                <updatePolicy>never</updatePolicy>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
    </repositories>
 
    <pluginRepositories>
        <pluginRepository>
            <id>adobe-public-releases</id>
            <name>Adobe Basel Public Repository</name>
            <url>https://repo.adobe.com/nexus/content/groups/public</url>
            <releases>
                <enabled>true</enabled>
                <updatePolicy>never</updatePolicy>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </pluginRepository>
    </pluginRepositories>
</profile>
 
</profiles>
 
  
   
  <activeProfiles>
    <activeProfile>adobe-public</activeProfile>
  </activeProfiles>
  
</settings>
====================================

**Comment by dhulipudi** [comment]
Now, I am able to build the project successfully.

**Comment by PSIPhone** [comment]
> Use mvn -PautoInstallPackage -Padobe-public clean install command.

It works but gives another error:

Unknown lifecycle phase "command". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>.

**Comment by godanny86** [comment]
> > Use mvn -PautoInstallPackage -Padobe-public clean install command.
> 
> It works but gives another error:
> 
> package javax.annotation does not exist

hi @Mohd-Aamir-M do you mind creating a new issue for this? Please detail the AEM version, Java version, maven version...

**Comment by Mohd-Aamir-M** [comment]
Hi @godanny86 ,
Here is my configuration.

JAVA 

java 11.0.1 2018-10-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.1+13-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.1+13-LTS, mixed mode)


MAVEN 3.6.0

I have created a project from this command.
mvn org.apache.maven.plugins:maven-archetype-plugin:2.4:generate -DarchetypeGroupId=com.adobe.granite.archetypes -DarchetypeArtifactId=aem-project-archetype -DarchetypeVersion=13 -DarchetypeCatalog=https://repo.adobe.com/nexus/content/groups/public/

Archtype version 13.

**Comment by godanny86** [comment]
Hi @Mohd-Aamir-M , currently the tutorial doesn't support Java 11. We are close to releasing an update. In the mean time, you can downgrade to Java 8 or you can try generating the project using Archetype version 18: https://github.com/adobe/aem-project-archetype/releases/tag/aem-project-archetype-18. Not everything will match exactly but you should still be able to follow the tutorial...

**Comment by Mohd-Aamir-M** [comment]
> Hi @Mohd-Aamir-M , currently the tutorial doesn't support Java 11. We are close to releasing an update. In the mean time, you can downgrade to Java 8 or you can try generating the project using Archetype version 18: https://github.com/adobe/aem-project-archetype/releases/tag/aem-project-archetype-18. Not everything will match exactly but you should still be able to follow the tutorial...
> 
> In the future, please create a New Issue...

Ok, i am going to try with Java 8. Thanks and i am following this tutorial. https://helpx.adobe.com/experience-manager/using/maven_arch13.html

Correct me please, if I am doing something wrong.

**Comment by Mohd-Aamir-M** [comment]
> Hi @Mohd-Aamir-M , currently the tutorial doesn't support Java 11. We are close to releasing an update. In the mean time, you can downgrade to Java 8 or you can try generating the project using Archetype version 18: https://github.com/adobe/aem-project-archetype/releases/tag/aem-project-archetype-18. Not everything will match exactly but you should still be able to follow the tutorial...
> 
> In the future, please create a New Issue...

Do i have to install AEM seperate or it is installed automatically when i run following command for community version. I am using Mac.

mvn org.apache.maven.plugins:maven-archetype-plugin:2.4:generate -DarchetypeGroupId=com.adobe.granite.archetypes -DarchetypeArtifactId=aem-project-archetype -DarchetypeVersion=13 -DarchetypeCatalog=https://repo.adobe.com/nexus/content/groups/public/
