### ISSUE TITLE
Importing Maven project has build errors

### ISSUE THREAD

**Issue by famu1hundred** [Adobe-Marketing-Cloud/aem-guides-wknd#22]
Imported maven project ui.content, ui.apps & core. Build has errors

Description	Resource	Path	Location	Type
No DS descriptor found at path target/classes/OSGI-INF/com.adobe.aem.guides.wknd.core.filters.LoggingFilter.xml.	MANIFEST.MF	/aem-guides-wknd.core/target/classes/META-INF	Unknown	Sling IDE Validation Marker
No DS descriptor found at path target/classes/OSGI-INF/com.adobe.aem.guides.wknd.core.listeners.SimpleResourceListener.xml.	MANIFEST.MF	/aem-guides-wknd.core/target/classes/META-INF	Unknown	Sling IDE Validation Marker
No DS descriptor found at path target/classes/OSGI-INF/com.adobe.aem.guides.wknd.core.schedulers.SimpleScheduledTask.xml.	MANIFEST.MF	/aem-guides-wknd.core/target/classes/META-INF	Unknown	Sling IDE Validation Marker
No DS descriptor found at path target/classes/OSGI-INF/com.adobe.aem.guides.wknd.core.servlets.SimpleServlet.xml.	MANIFEST.MF	/aem-guides-wknd.core/target/classes/META-INF	Unknown	Sling IDE Validation Marker

**Comment by godanny86** [comment]
Thanks @famu1hundred. Yes I think these errors are present when creating from the aem project archetype and should be cleaned up. However they should not prevent you from building and deploying the project to AEM.
