### ISSUE TITLE
Google font @import not loaded at the top

### ISSUE THREAD

**Issue by godanny86** [Adobe-Marketing-Cloud/aem-guides-wknd#25]
The @import is not loaded at the top of clientlib-base.css thus not requesting the google fonts. Need to re-work the order of how the client libraries are loaded.

Thanks @justinedelson for reporting!

**Comment by justinedelson** [comment]
Here's how I worked around this problem:
1. Create a separate clientlib at /apps/wknd/clientlibs/clientlib-font with the category wknd.font
2. Create a css file in this clientlib with just these two lines:
    @charset "UTF-8";
@import url('https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600|Asar');

**Comment by godanny86** [comment]
Fixed with https://github.com/Adobe-Marketing-Cloud/aem-guides-wknd/pull/26/files
