### ISSUE TITLE
error - mvn -PautoInstallPackage clean install

### ISSUE THREAD

**Issue by bertieucbs** [Adobe-Marketing-Cloud/aem-guides-wknd#32]
I am on 6.4 and when trying to run mvn -PautoInstallPackage clean install getting following

[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Unresolveable build extension: Plugin com.day.jcr.vault:content-package-maven-plugin:0.5.1 or one of its dependencies could not be resolved: Failure to find com.day.jcr.vault:content-package-maven-plugin:jar:0.5.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced @ 
[ERROR] Unknown packaging: content-package @ com.adobe.aem.guides:aem-guides-wknd.ui.apps:[unknown-version], /Users/username/Documents/Tech/Adobe/code/wknd_tutorial/aem-guides-wknd/ui.apps/pom.xml, line 34, column 16
[ERROR] Unresolveable build extension: Plugin com.day.jcr.vault:content-package-maven-plugin:0.5.1 or one of its dependencies could not be resolved: Failure to find com.day.jcr.vault:content-package-maven-plugin:jar:0.5.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced @ 
[ERROR] Unknown packaging: content-package @ com.adobe.aem.guides:aem-guides-wknd.ui.content:[unknown-version], /Users/username/Documents/Tech/Adobe/code/wknd_tutorial/aem-guides-wknd/ui.content/pom.xml, line 34, column 16
 @ 
[ERROR] The build could not read 2 projects -> [Help 1]
[ERROR]   
[ERROR]   The project com.adobe.aem.guides:aem-guides-wknd.ui.apps:0.0.1-SNAPSHOT (/Users/username/Documents/Tech/Adobe/code/wknd_tutorial/aem-guides-wknd/ui.apps/pom.xml) has 2 errors
[ERROR]     Unresolveable build extension: Plugin com.day.jcr.vault:content-package-maven-plugin:0.5.1 or one of its dependencies could not be resolved: Failure to find com.day.jcr.vault:content-package-maven-plugin:jar:0.5.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 2]
[ERROR]     Unknown packaging: content-package @ com.adobe.aem.guides:aem-guides-wknd.ui.apps:[unknown-version], /Users/username/Documents/Tech/Adobe/code/wknd_tutorial/aem-guides-wknd/ui.apps/pom.xml, line 34, column 16
[ERROR]   
[ERROR]   The project com.adobe.aem.guides:aem-guides-wknd.ui.content:0.0.1-SNAPSHOT (/Users/username/Documents/Tech/Adobe/code/wknd_tutorial/aem-guides-wknd/ui.content/pom.xml) has 2 errors
[ERROR]     Unresolveable build extension: Plugin com.day.jcr.vault:content-package-maven-plugin:0.5.1 or one of its dependencies could not be resolved: Failure to find com.day.jcr.vault:content-package-maven-plugin:jar:0.5.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 2]
[ERROR]     Unknown packaging: content-package @ com.adobe.aem.guides:aem-guides-wknd.ui.content:[unknown-version], /Users/username/Documents/Tech/Adobe/code/wknd_tutorial/aem-guides-wknd/ui.content/pom.xml, line 34, column 16
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/PluginManagerException
WKMUS2891017:aem-guides-wknd username$ vlt --version
-bash: vlt: command not found
WKMUS2891017:aem-guides-wknd username$ mvn -PautoInstallPackage clean install
[INFO] Scanning for projects...
[WARNING] The POM for com.day.jcr.vault:content-package-maven-plugin:jar:0.5.1 is missing, no dependency information available
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Unresolveable build extension: Plugin com.day.jcr.vault:content-package-maven-plugin:0.5.1 or one of its dependencies could not be resolved: Failure to find com.day.jcr.vault:content-package-maven-plugin:jar:0.5.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced @ 
[ERROR] Unknown packaging: content-package @ com.adobe.aem.guides:aem-guides-wknd.ui.apps:[unknown-version], /Users/username/Documents/Tech/Adobe/code/wknd_tutorial/aem-guides-wknd/ui.apps/pom.xml, line 34, column 16
[ERROR] Unresolveable build extension: Plugin com.day.jcr.vault:content-package-maven-plugin:0.5.1 or one of its dependencies could not be resolved: Failure to find com.day.jcr.vault:content-package-maven-plugin:jar:0.5.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced @ 
[ERROR] Unknown packaging: content-package @ com.adobe.aem.guides:aem-guides-wknd.ui.content:[unknown-version], /Users/username/Documents/Tech/Adobe/code/wknd_tutorial/aem-guides-wknd/ui.content/pom.xml, line 34, column 16
 @ 
[ERROR] The build could not read 2 projects -> [Help 1]
[ERROR]   
[ERROR]   The project com.adobe.aem.guides:aem-guides-wknd.ui.apps:0.0.1-SNAPSHOT (/Users/username/Documents/Tech/Adobe/code/wknd_tutorial/aem-guides-wknd/ui.apps/pom.xml) has 2 errors
[ERROR]     Unresolveable build extension: Plugin com.day.jcr.vault:content-package-maven-plugin:0.5.1 or one of its dependencies could not be resolved: Failure to find com.day.jcr.vault:content-package-maven-plugin:jar:0.5.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 2]
[ERROR]     Unknown packaging: content-package @ com.adobe.aem.guides:aem-guides-wknd.ui.apps:[unknown-version], /Users/username/Documents/Tech/Adobe/code/wknd_tutorial/aem-guides-wknd/ui.apps/pom.xml, line 34, column 16
[ERROR]   
[ERROR]   The project com.adobe.aem.guides:aem-guides-wknd.ui.content:0.0.1-SNAPSHOT (/Users/username/Documents/Tech/Adobe/code/wknd_tutorial/aem-guides-wknd/ui.content/pom.xml) has 2 errors
[ERROR]     Unresolveable build extension: Plugin com.day.jcr.vault:content-package-maven-plugin:0.5.1 or one of its dependencies could not be resolved: Failure to find com.day.jcr.vault:content-package-maven-plugin:jar:0.5.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 2]
[ERROR]     Unknown packaging: content-package @ com.adobe.aem.guides:aem-guides-wknd.ui.content:[unknown-version], /Users/username/Documents/Tech/Adobe/code/wknd_tutorial/aem-guides-wknd/ui.content/pom.xml, line 34, column 16
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/PluginManagerException

**Comment by pnyiu** [comment]
Try below:
mvn -PautoInstallPackage **-Padobe-public** clean install

**Comment by godanny86** [comment]
@bertieucbs I have updated: https://helpx.adobe.com/experience-manager/kt/sites/using/getting-started-wknd-tutorial-develop/part1.html#deploy-project to include some instructions on adding the adobe-public repo to a users  .m2/settings.xml. I think adding the nexus repositories to your settings.xml is a good practice but as @pnyiu mentions, you can also add the side profile of -Padobe-public in the command.
