### ISSUE TITLE
Add maven-sling-plugin to pom.xml

### ISSUE THREAD

**Issue by pnyiu** [Adobe-Marketing-Cloud/aem-guides-wknd#34]
Is it possible to add below plugin in build section to core/pom.xml? So that, it will deploy the bundle to AEM.

![image](https://user-images.githubusercontent.com/851417/45793632-a8b7d800-bcc5-11e8-88cf-b61fd82bbeeb.png)

mvn clean install 

[INFO] --- maven-sling-plugin:2.2.0:install (install-bundle) @ aem-guides-wknd.core ---
[INFO] Installing Bundle com.adobe.aem.guides.wknd-sites-guide(/root/aem_project/aem-guides-wknd/core/target/aem-guides-wknd.core-0.0.1-SNAPSHOT.jar) to http://localhost:4502/system/console via WebConsole
[INFO] Bundle installed

**Comment by godanny86** [comment]
@pnyiu does this not work with as is with:

`mvn -PautoInstallBundle clean install` ?

**Comment by pnyiu** [comment]
@godanny86 Yes, it works. 

I just wonder if we can include the `maven-sling-plugin` and `content-package-maven-plugin` to the pom.xml for package type as bundle and content-package respectively. Then, we can simply use `mvn clean install` to build and install all modules with adobe-public profile activated by default.

**Comment by godanny86** [comment]
@pnyiu we will be updating the project to use the latest [Maven Archetype 15](https://github.com/Adobe-Marketing-Cloud/aem-project-archetype). If you think this is something that should be part of the default archetype I would comment on that project. Thank you!
