### ISSUE TITLE
WKDN.Structure component group not visible

### ISSUE THREAD

**Issue by zwaldeck** [Adobe-Marketing-Cloud/aem-guides-wknd#35]
The WKDN.Structure component group is not visible for me when I edit template types (Part 2 of the tutorial) below the code of my header component jcr:

`<?xml version="1.0" encoding="UTF-8"?>
<jcr:root
        xmlns:sling="http://sling.apache.org/jcr/sling/1.0"
        xmlns:jcr="http://www.jcp.org/jcr/1.0"
        jcr:primaryType="cq:Component"
        componentGroup="WKND.Structure"
        jcr:description="Page Header with navigation"
        jcr:title="WKND Page Header"/>
`

**Comment by godanny86** [comment]
Hi @zwaldeck a couple of things to verify:

1. On your local AEM instance in CRXDE Lite can you verify that the Header component is there?
2. Make sure the Header component has the `cq:dialog` beneath it


![](https://helpx.adobe.com/content/dam/help/en/experience-manager/kt/sites/using/getting-started-wknd-tutorial-develop/part2/_jcr_content/main-pars/procedure_288740576/proc_par/step_2098964216/step_par/image/crx-de.png)

**Comment by godanny86** [comment]
@zwaldeck any update on this? Were you able to resolve this issue?

**Comment by godanny86** [comment]
@zwaldeck going to close this. Feel free to re-open if you are stuck...

**Comment by parvathyc** [comment]
That helped me. Thanks!
