### ISSUE TITLE
Getting React Error

### ISSUE THREAD

**Issue by vivekdhiman** [Adobe-Marketing-Cloud/aem-guides-wknd#37]
Hi,

While using SPA, I am facing below problem. Due to this components are not rendering properly.
![image](https://user-images.githubusercontent.com/7066652/47729536-55eb1c00-dc86-11e8-84f7-07f6c2ea9617.png)
Thanks

**Comment by godanny86** [comment]
hi @vivekdhiman do you mind posting in https://github.com/Adobe-Marketing-Cloud/aem-guides-wknd-events/issues ?
