### ISSUE TITLE
Bootstrap version 4

### ISSUE THREAD

**Issue by pnyiu** [Adobe-Marketing-Cloud/aem-guides-wknd#48]
May I know whether AEM 6.4 supports Bootstrap 4? Please let me know if it is not proper to ask this question here. Thanks.

**Comment by godanny86** [comment]
hi @pnyiu the compiled version of Bootstrap 4 can be used with AEM 6.4, as this is just CSS and can be served from a client library. If you wish to leverage the full power of Bootstrap, by customizing the pre-compiled Sass files, this cannot be done inside AEM natively, as AEM does not have a Sass compiler. 

Instead the approach would be to have a standalone webpack project that leverages [aem-clientlib-generator](https://www.npmjs.com/package/aem-clientlib-generator) and [frontend-maven-plugin](https://github.com/eirslett/frontend-maven-plugin) to inject the customized Bootstrap as a clientlibrary at build time. This is the approach used for SPA editor support and can be followed with or without the SPA itself, see [Getting Started with the AEM SPA Editor - Chapter 0](https://helpx.adobe.com/experience-manager/kt/sites/using/getting-started-spa-wknd-tutorial-develop/react/chapter-0.html#approach) for more details...
