### ISSUE TITLE
build failure when running  mvn -PautoInstallPackage -Padobe-public clean install

### ISSUE THREAD

**Issue by daddyschmack** [Adobe-Marketing-Cloud/aem-guides-wknd#54]
`
[INFO] --- content-package-maven-plugin:1.0.2:install (install-package) @ aem-guides-wknd.ui.apps ---
[INFO] Installing aem-guides-wknd.ui.apps (/Users/johnjaeckle/aem-guides-wknd/ui.apps/target/aem-guides-wknd.ui.apps-0.0.1-SNAPSHOT.zip) to http://localhost:4502/crx/packmgr/service.jsp
[INFO] I/O exception (java.net.ConnectException) caught when processing request: Connection refused
[INFO] Retrying request
[INFO] I/O exception (java.net.ConnectException) caught when processing request: Connection refused
[INFO] Retrying request
[INFO] I/O exception (java.net.ConnectException) caught when processing request: Connection refused
[INFO] Retrying request
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for aem-guides-wknd 0.0.1-SNAPSHOT:
[INFO] 
[INFO] aem-guides-wknd .................................... SUCCESS [  0.299 s]

[INFO] WKND Sites Project - Core .......................... SUCCESS [  4.055 s]
[INFO] WKND Sites Project - UI apps ....................... FAILURE [  2.405 s]

[INFO] WKND Sites Project - UI content .................... SKIPPED
[INFO] WKND Sites Project - Integration Tests Bundles ..... SKIPPED
[INFO] WKND Sites Project - Integration Tests Launcher .... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.093 s
[INFO] Finished at: 2018-12-18T19:24:48-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.day.jcr.vault:content-package-maven-plugin:1.0.2:install (install-package) on project aem-guides-wknd.ui.apps: Connection refused -> [Help 1]
`

Why is this happening?   Everything else seems to get through?  
I have to say I'm somewhat frustrated.  I would have thought the tutorial setup would have been bulletproof.  I did the first steps of the angular part and it didn't have errors. 
I did check to make sure the nexus was part of my settings.xml per a suggestion in a different issue.

Thanks in advance.

**Comment by godanny86** [comment]
hi @daddyschmack from the error it looks the package isn't able to be deployed to a local aem instance running at http://localhost:4502. Is AEM running on that port and able to be reached? Has the admin password changed?

Also just a heads up this is the repo for the WKND Sites tutorial - https://helpx.adobe.com/experience-manager/kt/sites/using/getting-started-wknd-tutorial-develop.html 
vs. the Angular SPA Editor tutorial - https://helpx.adobe.com/experience-manager/kt/sites/using/getting-started-wknd-tutorial-develop.html

**Comment by daddyschmack** [comment]
@godanny86 , thanks for answering, as it turns out, I'm trying to run the Angular WKND tutorial:
https://helpx.adobe.com/experience-manager/kt/sites/using/getting-started-wknd-tutorial-develop.html
the project setup for maven, but this error seemed to be the closest error to what I was receiving.  Do I need to open a different issue?

**Comment by godanny86** [comment]
hi @daddyschmack if you don't mind, please raise issues for the Angular tutorial here: https://github.com/Adobe-Marketing-Cloud/aem-guides-wknd-events/issues
