### ISSUE TITLE
reopening - build failure when running mvn -PautoInstallPackage -Padobe-public clean install

### ISSUE THREAD

**Issue by daddyschmack** [Adobe-Marketing-Cloud/aem-guides-wknd#55]
HI @godanny86, 
I'm reopening this issues #54. 
I did try the suggestion in #32. 
 It appears to have the same connectivity issue as:
https://github.com/Adobe-Marketing-Cloud/aem-guides-wknd-events/issues/45.
There is no "day" directory available.

I'm trying to build the server so that I can run the Angular tutorial with the rich content.
I have determined that there is a problem reaching this URL:
com.day.jcr.vault:content-package-maven-plugin:1.0.2:install (install-package) on project aem-guides-wknd.ui.apps: Connection refused -> [Help 1]

Can you please confirm the directory exists and that if so, it's available externally?

Thanks!

**Comment by daddyschmack** [comment]
Hi @godanny86 , 
I think I finally understand!  I don't have the server running.  So we can close this.  So it's the same issue on both questions.  However, can we go to the other issue with trying to upload and deploy the snapshots on a pre-existing server?

**Comment by godanny86** [comment]
Ah great! Sorry for the back and forth, I didn't understand what was happening until you mentioned building a server. I'll try to answer on the other thread
