### ISSUE TITLE
Editable Templates - Text V2 

### ISSUE THREAD

**Issue by sreenu539** [Adobe-Marketing-Cloud/aem-guides-wknd#56]
what user is used to author Text V2 component. 

Issue 1:
I had problems using Text V1 - as content author.  Paragraph pop over not displayed, paragraph icon is getting disabled on click. 

Issue 2:
I overwrote cq:inplaceediting with config node having htmlrules node to do bold to strong, italics to em markup.

bold to strong, italics to em worked for admin user but did not work for content author - markup generated has bold tag rather than strong tag.

What is the best practice to use core components - for content authors group users. How to do any customization such as htmlrules on top of V1 or V2 component?

Thanks,
Sri

**Comment by godanny86** [comment]
@sreenu539 thank you for raising this. Will need to investigate. As this is related to Core Components in general you may want to raise an issue with the Core Component project: https://github.com/adobe/aem-core-wcm-components/issues
